version: "3"

services:
  nginx:
    image: nginx:1.23
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - /var/www/html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
